# checkov:skip=CKV_DOCKER_2: no healthcheck, external healthcheck will be used
FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/docker-chainguard-remote/ssc-spc.gc.ca/python:3.13.3
WORKDIR /app
COPY app.py .
EXPOSE 8080
CMD ["python", "app.py"]
