# checkov:skip=CKV_DOCKER_2: no healthcheck, external healthcheck will be used
FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/docker/library/python:3.13-slim
WORKDIR /app
COPY app.py .
EXPOSE 8080
CMD ["python", "app.py"]
