# checkov:skip=CKV_DOCKER_2: no healthcheck, external healthcheck will be used
FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/docker-chainguard-remote/ssc-spc.gc.ca/node:24.1.0
WORKDIR /app
COPY app.js .
EXPOSE 8080
CMD ["node", "app.js"]
