# checkov:skip=CKV_DOCKER_2: no healthcheck, external healthcheck will be used
# checkov:skip=CKV_DOCKER_3: no user, not used for demo file
FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/docker/library/node:20-slim
WORKDIR /app
COPY app.js .
EXPOSE 8080
CMD ["node", "app.js"]
