FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/docker-chainguard-remote/ssc-spc.gc.ca/jdk@sha256:204d1c2bd22489640fe000034a864caf65650bf5ee44cd506fb6fe1ded36b18d
WORKDIR /app
COPY src/main/java/com/example/*.java ./
RUN javac *.java

FROM artifacts-artefacts.devops.cloud-nuage.canada.ca/docker-chainguard-remote/ssc-spc.gc.ca/jre@sha256:3503acc346f687b41fdfeb4d562f39b643bcfdecd445e268d7ba8b0b3ebe27e3
WORKDIR /app
COPY --from=builder /app/*.class ./
EXPOSE 8080
CMD ["java", "App"]
